# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.labelUsername = QtWidgets.QLabel(Dialog)
        self.labelUsername.setGeometry(QtCore.QRect(70, 90, 60, 16))
        self.labelUsername.setObjectName("labelUsername")
        self.labelPassword = QtWidgets.QLabel(Dialog)
        self.labelPassword.setGeometry(QtCore.QRect(70, 140, 60, 16))
        self.labelPassword.setObjectName("labelPassword")
        self.lineEdiUsername = QtWidgets.QLineEdit(Dialog)
        self.lineEdiUsername.setGeometry(QtCore.QRect(150, 90, 113, 21))
        self.lineEdiUsername.setObjectName("lineEdiUsername")
        self.lineEditPassword = QtWidgets.QLineEdit(Dialog)
        self.lineEditPassword.setGeometry(QtCore.QRect(150, 140, 113, 21))
        self.lineEditPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEditPassword.setObjectName("lineEditPassword")
        self.pushButtonLogin = QtWidgets.QPushButton(Dialog)
        self.pushButtonLogin.setGeometry(QtCore.QRect(70, 220, 113, 32))
        self.pushButtonLogin.setObjectName("pushButtonLogin")
        self.pushButtonCancel = QtWidgets.QPushButton(Dialog)
        self.pushButtonCancel.setGeometry(QtCore.QRect(210, 220, 113, 32))
        self.pushButtonCancel.setObjectName("pushButtonCancel")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.labelUsername.setText(_translate("Dialog", "帳號"))
        self.labelPassword.setText(_translate("Dialog", "密碼"))
        self.pushButtonLogin.setText(_translate("Dialog", "登入"))
        self.pushButtonCancel.setText(_translate("Dialog", "取消"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
